version: "3.8"
services:
  ansible:
    build: ./ansible/
    tty: true
    image: ansible
    container_name: ansible
    hostname: ansible
    volumes:
      - ./ansible/playbooks:/playbooks
      - ./ansible/hosts:/etc/ansible/hosts
    ports:
      - 2222:22
    environment:
      - DO_API_TOKEN=${DO_API_TOKEN}

  jenkins:
    build: ./jenkins/
    privileged: true
    user: root
    ports:
      - 9090:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
