- name: Destroy Digital Ocean
  hosts: localhost
  connection: local
  tasks:
    - name: Destroy (delete) an existing DigitalOcean Kubernetes cluster
      community.digitalocean.digital_ocean_kubernetes:
        state: absent
        delete_all: true
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        name: miniprojet-k8s
