- name: Ensure Nginx is installed
  hosts: localhost
  connection: local
  tasks:
    - name: Destroy (delete) an existing DigitalOcean Kubernetes cluster
      community.digitalocean.digital_ocean_kubernetes:
        state: absent
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        name: miniprojet-k8s
