- name: Ensure Nginx is installed
  hosts: webservers
  user: ansible
  tasks:
    - name: add Docker apt-key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker-apt-keyring.asc
        mode: "0644"
        force: true
      become: yes

    - name: add Docker's APT repository
      apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }} signed-by=/etc/apt/keyrings/docker-apt-keyring.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
      become: yes

    - name: Install docker (rootless) & docker compose
      apt:
        name:
          - docker.io
          - docker-ce-rootless-extras
          - uidmap
          - docker-compose-plugin
        state: present
      become: yes

    - name: Enable user lingering
      ansible.builtin.command: loginctl enable-linger ansible
      become: yes
      args:
        creates: /var/lib/systemd/linger/ansible

    - name: Setup rootless docker
      ansible.builtin.command: dockerd-rootless-setuptool.sh install
